site_name: RefMD Documentation
site_description: Official guide for using, operating, and extending RefMD.
repo_url: https://github.com/refmdio/refmd
repo_name: refmdio/refmd
edit_uri: edit/main/docs/

nav:
  - Overview: index.md
  - Editor Guide: editor.md
  - System Architecture: architecture.md
  - Plugin Platform:
      - Overview: plugins/index.md
      - Manifest Specification: plugins/manifest.md
      - Development Guide: plugins/development.md
      - Plugin API Reference: plugins/api.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: "JetBrains Mono"

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/refmdio/refmdio
      name: RefMD on GitHub

extra_css: []
extra_javascript: []
